### ISSUE TITLE
Is.SPA.converge missing?

### ISSUE THREAD

**Issue by guidebortoli** [saigegit/SAIGE#20]
Hi, I've seen on my result files that I don't have the Is.SPA.converge column...
Perhaps it was replaced by the column Is.SPA (TRUE if converged and FALSE if not)?

Thank you

**Comment by saigegit** [comment]
Hi @guidebortoli, 

You are correct.  Is.SPA.converge is replaced with Is.SPA, because this column indicates whether SPA has been successfully applied. Is.SPA=FALSE can be due to SPA is not applied because the absolute value of z score is not greater than `SPAcutoff` or it can be because SPA did not converge. 

Thanks,
Wei
