### ISSUE TITLE
Calculating odds ratios from saige-gene summary stats

### ISSUE THREAD

**Issue by oalavijeh** [saigegit/SAIGE#66]
In keeping with this issue:https://github.com/weizhouUMICH/SAIGE/issues/43

Could I ask if there is example code for this? I have summary stats from a SAIGE-GENE analysis collapsed per gene. How would I apply Firth testing to this dataset to get the OR. I have been pulling the variants that make up the signal and simply counting how many of these are found in my cases/controls and doing a simple OR calculation this way. Is there a better method using summary stats?

Many thanks

**Comment by weizhou0** [comment]
Hi @oalavijeh, 

As far as I know, there is not a way to use the single-variant summary stats to obtain an OR with firth approximation. Are you trying to get the OR for a gene or a set from the burden test? If so, the BETA_Burden for each set is included in the output.   You may just set --is_Firth_beta = TRUE and set a p-value cutoff to apply the Firth approximation: --pCutoffforFirth = 0.01. Since beta weights are used to weight rarer variants higher than common variants, the beta or OR can be difficult to interpret. You may consider do not apply weights using --is_no_weight_in_groupTest=TRUE to obtain the raw OR. 

Thanks,
Wei
