### ISSUE TITLE
Error while installing saige in slurm module

### ISSUE THREAD

**Issue by akhilpampana** [saigegit/SAIGE#97]
ello,

I am trying to Saige and I am getting an error like this.

```Downloading https://github.com/statgen/savvy/archive/v2.1.0.tar.gz
Unexpected error: <class 'OSError'>
[Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
Failed to build package statgen/savvy
```

May I know how to rectify this error?

~Akhil

**Comment by saigegit** [comment]
Hi Akhil, 

The error is due to the savvy library. Sometimes the the package installation fails due to an internet hiccup. Would it be possible to use the conda environment for installation?  That would be the easiest solution. 
[https://saigegit.github.io/SAIGE-doc/docs/Installation_conda.html](https://saigegit.github.io/SAIGE-doc/docs/Installation_conda.html
)

Thanks,
Wei
